name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          apt-get update && apt-get install -y make sudo gawk
          apt-get install -y curl python3 python3-pip texlive-xetex python3-venv python3-requests pandoc
          apt-get install -y nodejs npm 
          npm install --global cowel

      - name: Build site
        run: python3 scripts/ci.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'generated'

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
